language: python
python:
- 3.5.2
install: pip install -r requirements.txt
script: nosetests
deploy:
  provider: heroku
  api_key:
    secure: GwwLfDT5MgjaPo8OLKc6MYndYnICucFImYGS5v0w9+iN7OLwy+dpWjrLJj7uuRYPcT4DVUoxx2S9tYD49qtcnUe6VrR/W6Gq1+rVntU4YtmjRjs2Py79sEjPeOzkfbC6g7dnoZQKloAytfWKBE0fUbzM2pRYOHDNCzgB9KmH7o8mRtClGalDkNX5rUD30sX2wYQ32TisAHazgCSkqKMQs/4USGCYxGpIjONc0PsO3ylaWybgX/hnb0SBqmWe+typkfpq4eOrsIAAcrQ0oXJ+VsaR0dw0HKHC7GnN33f4dej34gcO81kW6sLeRWxydRY+zG7OAq0wWZMW8sJNLljsmvHfS7t+IY9UkQoSF8jZrFXAuSv/8dUuokDQ7FlDb63UtQ/T9nPn/hnphASF/VDSIlFlrE0XZXObR4DW3J6e8m1BVy5m5UcSKN4HsdzgLCbQtpnN2yQ738U6VWRrh1m6VVQI/7bP7/4XTE+2s9eC1beRmlwYQUfhhTogHfUVxkNH147ntEvim2xUDdHVQ4mf1zO4i57exyBVNmFIsOmRj0p/ZK86tz9EtGN2s6jeWoWCIv+PHnuSJjEavHmH0zEHMgcVdgGusXAB/Z4gfmgP9Q5Gz/s7FcWv0qiOuJiGsFLdS4pSCapm7N26wcvEkF1fFb4xc/p24Qj6PpEhbXGNq1o=
  app: olimpicolombia
  on:
    repo: Rocket-Team/olimpiColombia
