# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 23:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0002_auto_20160815_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=25)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('birth_place', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('age', models.IntegerField()),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('coach_name', models.CharField(max_length=50)),
                ('link_video', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('state', models.CharField(max_length=20)),
                ('result', models.CharField(max_length=20)),
                ('modality', models.CharField(max_length=20)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Athlete')),
            ],
        ),
        migrations.CreateModel(
            name='VisitRegistry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_fb', models.CharField(max_length=25)),
                ('datetime', models.DateTimeField()),
                ('ip', models.CharField(max_length=15)),
                ('user_type', models.CharField(max_length=15)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Athlete')),
                ('user_app', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='sport',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Sport'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Sport'),
        ),
    ]
