# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_athlete_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sport',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='athlete',
            name='highlight',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
