# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20160821_0941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='athlete',
            options={'ordering': ['last_name']},
        ),
        migrations.AddField(
            model_name='athlete',
            name='photo',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
