# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20160821_1515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduleitem',
            options={'ordering': ['datetime']},
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='link_video',
        ),
        migrations.AddField(
            model_name='athlete',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=b'media/video'),
        ),
    ]
