# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20160823_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='highlight',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='identification',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='photo',
        ),
        migrations.AlterField(
            model_name='athlete',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video'),
        ),
    ]
