# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20160831_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='fotos'),
        ),
    ]
